### ISSUE TITLE
Branch AudioSource: Teleport not working properly

### ISSUE THREAD

**Issue by smeerws** [4ahmnm2021-G3-G4/01-maze-audiocode-sfeld#11]
Possible Solution: 

Disable Floor GameObject, 
Add to Terrain a Mesh Renderer and a Teleport Script, uncheck Marker Active in Teleport Area Component
![TeleportTerrain](https://user-images.githubusercontent.com/28704310/122684759-b6e50b00-d207-11eb-8c62-3375dcc03996.JPG)

**Comment by feldbacherSimone** [comment]
I already fixed this issue in the main branch, should I delete the other branches to avoid confusion? @smeerws
