### ISSUE TITLE
Accidentally Named a commit wrong, don't know how to change the commit name after pushing 

### ISSUE THREAD

**Issue by feldbacherSimone** [4ahmnm2021-G3-G4/01-maze-audiocode-sfeld#7]
Nachdem ich mein gitignore geändert habe, wollte ich den alten name pasten, habe aber aus versehen den commit "Asstes/SteamVR" benannt. Da ich schon mehrere commits dananch erstellt habe bin ich mir nicht sicher wie ich den Namen jetzt noch anderen kann , da es nun so wirkt als hätte ich SteamVR mit commitet (was nicht der Fall ist)

**Comment by smeerws** [comment]
https://github.com/4ahmnm2021-G3-G4/01-maze-audiocode-sfeld/issues/8

Da ist eine Anleitung drinnen wie es gehen kann.
Lasse es einfachen, passt so
